version: '3.8'

services:
  backend:
    build:  
      context: .
      dockerfile: backend.dockerfile
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment: 
      - PORT=8000
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DATABASE_URL=mongodb://root:password@mongodb:27017/overbooked_ai?authSource=admin
      - LLM_AGENT_URL=http://wiremock:8080
    depends_on:
      - wiremock
      - mongodb 

  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock:/home/wiremock
      - ./wiremock/mappings:/home/wiremock/mappings  # Mount mappings folder
      - ./wiremock/__files:/home/wiremock/__files  # Mount __files folder
    command: --verbose

  mongodb:
    image: mongo:latest  # Pull the latest MongoDB image
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password  # Set a root password
      - MONGO_INITDB_DATABASE=overbooked_ai  # Default database (optional)
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    # ports:
      # - "27017:27017"  # Expose MongoDB on port 27017 if needed. You can change this if needed

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
