services:
  frontend:
    build:  
      context: ./frontend
    command: yarn start
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - default
    
  backend:
    build:  
      context: ./backend
    command: yarn start
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    ports:
      - "8000:8000"
    environment: 
      - PORT=8000
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - DATABASE_URL=mongodb://root:password@mongodb:27017/overbooked_ai?authSource=admin
      - LLM_AGENT_URL=http://wiremock:8080
    depends_on:
      - wiremock
      - mongodb 
    networks:
      - default

  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8080:8080"
    volumes:
      - ./backend/wiremock:/home/wiremock
      - ./backend/wiremock/mappings:/home/wiremock/mappings  # Mount mappings folder
      - ./backend/wiremock/__files:/home/wiremock/__files  # Mount __files folder
    command: --verbose
    networks:
      - default

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=overbooked_ai
    volumes:
      - mongo_data:/data/db
    # Uncomment if you need MongoDB accessible from the host machine
    ports:
      - "27017:27017"
    networks:
      - default

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
